
OBJ_CHAINSAW_ID         = $005E
OBJ_TOOLS_ID            = $0098
OBJ_BOARDS_ID           = $00DF ; was id of hatch which changed to $01D3
OBJ_GASTANK_ID          = $00E2
OBJ_BOARDED_WINDOW_ID   = $0197
OBJ_SIGN_ID             = $01BF
OBJ_ROTTED_STAIRS_ID    = $01D4
OBJ_FIXED_STAIRS_ID     = $01D5
OBJ_TOP_OF_STAIRS_ID    = $01D6
OBJ_MODEL_ROOM_ENTRY_ID = $01DD

ROOM_LIBRARY_ID = $05
ROOM_MODEL_ID   = $35

ACTOR_SYD = $0001
